name: pmsn20232
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  uni_links: ^0.5.1
  url_launcher: ^6.0.0
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  video_player: ^2.6.1
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.1
  table_calendar: ^3.0.9
  provider: ^6.0.5
  flutter_slider_drawer: ^2.1.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  day_night_switcher: ^0.2.0+1
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/
